// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmHk4ZSGReM_uKbepzvHHITFxjBhHxPFk',
    appId: '1:22097502419:web:5d3790bef4e66e48f37426',
    messagingSenderId: '22097502419',
    projectId: 'restoran-pos-f37ae',
    authDomain: 'restoran-pos-f37ae.firebaseapp.com',
    storageBucket: 'restoran-pos-f37ae.firebasestorage.app',
    measurementId: 'G-J7XVKTC1TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfy6o3xDriNUlj1brdeGivLu50UHpMFss',
    appId: '1:22097502419:android:a50237f020c9d614f37426',
    messagingSenderId: '22097502419',
    projectId: 'restoran-pos-f37ae',
    storageBucket: 'restoran-pos-f37ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-0wCZmbsmhW3y4Xvm6XNUFtGoQIpn0Xc',
    appId: '1:22097502419:ios:72eaa7e5f872f9b3f37426',
    messagingSenderId: '22097502419',
    projectId: 'restoran-pos-f37ae',
    storageBucket: 'restoran-pos-f37ae.firebasestorage.app',
    iosBundleId: 'com.example.restoranPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-0wCZmbsmhW3y4Xvm6XNUFtGoQIpn0Xc',
    appId: '1:22097502419:ios:72eaa7e5f872f9b3f37426',
    messagingSenderId: '22097502419',
    projectId: 'restoran-pos-f37ae',
    storageBucket: 'restoran-pos-f37ae.firebasestorage.app',
    iosBundleId: 'com.example.restoranPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmHk4ZSGReM_uKbepzvHHITFxjBhHxPFk',
    appId: '1:22097502419:web:fd99c788213f5bb5f37426',
    messagingSenderId: '22097502419',
    projectId: 'restoran-pos-f37ae',
    authDomain: 'restoran-pos-f37ae.firebaseapp.com',
    storageBucket: 'restoran-pos-f37ae.firebasestorage.app',
    measurementId: 'G-W0S2MFGLW3',
  );
}
